spring.application.name=notification

server.port=8081

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=25
spring.mail.username=981abaafffe815
spring.mail.password=aabcdb485b0c6d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMS

# Whatsapp

# Telegram

# WeChat